import './style.css'
import { catchTheDots } from './src/catch-the-dots'
// import { catchTheDot } from './src/catch-the-dot'
// import { behaviorsubjectClickNums } from './src/behaviorsubject-click-nums'
// import { alphabetInvasion } from './src/alphabet-invasion'
// import { innerApp } from './src/innerApp'
// import { simpleDrag } from './src/simple-drag'
// import { delayDrag } from './src/delay-drag'
// import { multTrackDrag } from './src/mult-track-drag'
// import { registerForm } from './src/register-form'
// import { simpleCounter } from './src/simple-counter'
// import { fetchButton } from './src/fetch-button'
// import { simpleAutoComplete } from './src/simple-auto-complete'
// import {bmi} from './src/bmi'
// import {fetchDogAndCat} from './src/fetch-dog-and-cat'
// import {editTaskName} from './src/edit-task-name'
