import './style.css'
// import { innerApp } from './src/innerApp'
// import { simpleDrag } from './src/simple-drag'
// import { delayDrag } from './src/delay-drag'
import { multTrackDrag } from './src/mult-track-drag'
// import { simpleCounter } from './src/simple-counter'
// import { fetchButton } from './src/fetch-button'
// import { simpleAutoComplete } from './src/simple-auto-complete'
